name: Pipeline

on: [push]

jobs:
  run-prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: npm install
      - name: Check code formatting
        run: npm run prettier:check

  run-lint:
    runs-on: ubuntu-latest
    needs: run-prettier
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: npm install
      - name: Verify lint
        run: npm run lint

  run-build:
    runs-on: ubuntu-latest
    needs: run-lint
    env:
      NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
      NEXT_PUBLIC_SUPABASE_ROLE_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ROLE_KEY }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "22.x"
      - name: Install dependencies
        run: npm install
      - name: Try to build
        run: npm run build
